repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    exclude: ^(src)
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: local
  hooks:
    - id: cppcheck
      name: cppcheck
      entry: cppcheck
      language: system
      types_or: [c++, c]
      args: ["--error-exitcode=0"]
    - id: cpplint
      name: cpplint
      entry: cpplint
      language: system
      types_or: [c++, c]
      args: ["--filter=-whitespace/comments"]
    - id: clang-format
      name: clang-format
      entry: clang-format
      language: system
      types_or: [c, c++, cuda]
      args: ["-fallback-style=none", "-style=file", "-i"]
