# To use:
#
#   $ micromamba create -n readcon_dev -f conda-lock.yml # conda works for this as well
#   $ micromamba activate readcon_dev
#
name: readcon_dev
channels:
  - conda-forge
dependencies:
  - compilers
  - meson
  - ninja
  - cmake
  - pkg-config
  # Backports away from C++20
  - range-v3
  # Pinned
  - "eigen==3.4.0"
  - "fmt<=10"
  # Python helpers
  - pipx # conda-lock pdm towncrier
  - pre-commit
  # Optional
  - arrow-cpp
  - xtensor
  # Pre-commit
  - cpplint
  - cppcheck
  - clang-format
