[project]
name = "readCon"
version = "0.1.0"
description = "Add a short description here"
authors = ["Rohit Goswami <rog32@hi.is>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
range-v3 = "0.12.0.*"
pkgconfig = "1.5.5.*"
pkg-config = "0.29.2.*"
meson = "1.2.3.*"
cmake = "3.27.6.*"
ninja = "1.11.1.*"
fmt = "10.1.1.*"
gtest = "1.14.0.*"
