/*
 * TestConFrameVec.cc
 *
 *  Created on: 25 July 2024
 *      Author: Rohit Goswami
 *     Company: University of Iceland
 */

#include "../include/ReadCon.hpp"
#include <gtest/gtest.h>

using namespace yodecon::types;

TEST(ConFrameVecTest, Constructor) {
  ConFrameVec conFrameVec;
  conFrameVec.prebox_header = {"Generated by eOn", ""};
  conFrameVec.boxl = {25.0, 25.0, 25.0};
  conFrameVec.angles = {90.0, 90.0, 90.0};
  conFrameVec.postbox_header = {"", ""};
  conFrameVec.natm_types = 4;
  conFrameVec.natms_per_type = {2, 4, 6, 1};
  conFrameVec.masses_per_type = {15.99, 12.011, 1.008, 32.065};
  conFrameVec.symbol.push_back("O");
  conFrameVec.x.push_back(10.477713);
  conFrameVec.y.push_back(12.379463);
  conFrameVec.z.push_back(12.871778);
  conFrameVec.is_fixed.push_back(false);
  conFrameVec.atom_id.push_back(1);

  EXPECT_EQ("Generated by eOn", conFrameVec.prebox_header[0]);
  EXPECT_DOUBLE_EQ(25.0, conFrameVec.boxl[0]);
  EXPECT_DOUBLE_EQ(90.0, conFrameVec.angles[0]);
  EXPECT_EQ(4, conFrameVec.natm_types);
  EXPECT_EQ(2, conFrameVec.natms_per_type[0]);
  EXPECT_DOUBLE_EQ(15.99, conFrameVec.masses_per_type[0]);
  EXPECT_EQ("O", conFrameVec.symbol[0]);
  EXPECT_DOUBLE_EQ(10.477713, conFrameVec.x[0]);
  EXPECT_DOUBLE_EQ(12.379463, conFrameVec.y[0]);
  EXPECT_DOUBLE_EQ(12.871778, conFrameVec.z[0]);
  EXPECT_EQ(false, conFrameVec.is_fixed[0]);
  EXPECT_EQ(1, conFrameVec.atom_id[0]);
}

int main(int argc, char **argv) {
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
