name: Conda Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  buildmamba:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-2019}
          - {os: macOS-latest}
          - {os: ubuntu-latest}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Install Conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          environment-name: readcon_dev
          cache-environment: true
      - name: Build and Test
        shell: bash -l {0}
        run: |
          meson setup bbdir --prefix=$CONDA_PREFIX --libdir=lib -Dwith_tests=true -Dwith_fmt=true -Dwith_xtensor=true -Dwith_apache_arrow=true -Dwith_rangev3=true -Dwith_eigen=true
          meson compile -C bbdir -vvv
          meson test -C bbdir -vvv
